package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "audio_format",
    hdrs = [
        "audio_format.h",
    ],
)
